import { NextRequest, NextResponse } from "next/server"
import nodemailer from 'nodemailer'
import fs from 'fs'
import path from 'path'
import { prisma } from '@/lib/prisma'
import { getSessionFromCookie } from '@/lib/session'
import { NCFType } from '@/lib/ncf'

const CONFIG_FILE = path.join(process.cwd(), 'email-config.json')

interface BusinessSettings {
  name: string;
  rnc: string;
  address: string;
  phone: string;
  email: string;
  logo?: string;
}

interface BusinessSettings {
  name: string;
  rnc: string;
  address: string;
  phone: string;
  email: string;
  logo?: string;
}

// Get business settings from database
async function getBusinessSettings() {
  const settings = await prisma.setting.findMany({
    where: {
      key: {
        in: ['business_name', 'business_rnc', 'business_address', 'business_phone', 'business_email', 'business_logo']
      }
    }
  })

  const businessData: {
    name: string
    rnc: string
    address: string
    phone: string
    email: string
    logo?: string
  } = {
    name: 'GNTech Demo',
    rnc: '000-00000-0',
    address: 'Santo Domingo, República Dominicana',
    phone: '809-555-5555',
    email: 'info@gntech.com',
    logo: undefined
  }

  // Override with database values
  settings.forEach((setting: { key: string; value: string }) => {
    switch (setting.key) {
      case 'business_name':
        businessData.name = setting.value
        break
      case 'business_rnc':
        businessData.rnc = setting.value
        break
      case 'business_address':
        businessData.address = setting.value
        break
      case 'business_phone':
        businessData.phone = setting.value
        break
      case 'business_email':
        businessData.email = setting.value
        break
      case 'business_logo':
        businessData.logo = setting.value
        break
    }
  })

  return businessData
}

interface AlertData {
  type: string
  message: string
  severity: 'INFO' | 'WARNING' | 'CRITICAL' | 'DANGER'
  sequenceType: NCFType
  daysLeft?: number
  remaining?: number
  actionRequired: boolean
  autoGenerated: boolean
}

// Load email configuration from file
function loadEmailConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      const configData = fs.readFileSync(CONFIG_FILE, 'utf8')
      return JSON.parse(configData)
    }
  } catch (error) {
    console.error('Error loading email config:', error)
  }

  // Fallback to environment variables
  return {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true',
    tls: process.env.SMTP_TLS !== 'false',
    timeout: process.env.SMTP_TIMEOUT || '30000',
    user: process.env.SMTP_USER || '',
    password: process.env.SMTP_PASS || '',
    senderName: process.env.SMTP_SENDER_NAME || 'Sistema POS - GNTech'
  }
}

// Create email transporter
function createTransporter() {
  const emailConfig = loadEmailConfig()

  return nodemailer.createTransport({
    host: emailConfig.host,
    port: parseInt(emailConfig.port.toString()),
    secure: emailConfig.secure || parseInt(emailConfig.port.toString()) === 465,
    requireTLS: emailConfig.tls,
    tls: {
      // Office365 compatible TLS settings
      minVersion: 'TLSv1.2',
      ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384',
      rejectUnauthorized: false // Allow Office365 certificates
    },
    auth: {
      user: emailConfig.user,
      pass: emailConfig.password || process.env.SMTP_PASS || ''
    },
    connectionTimeout: parseInt(emailConfig.timeout || '30000'),
    greetingTimeout: 30000,
    socketTimeout: parseInt(emailConfig.timeout || '30000'),
    debug: process.env.NODE_ENV === 'development',
    logger: process.env.NODE_ENV === 'development'
  })
}

// Generate HTML email template for NCF alerts
function generateNCFAlertEmailHTML(alerts: AlertData[], businessSettings: BusinessSettings): string {
  const criticalAlerts = alerts.filter(a => a.severity === 'DANGER' || a.severity === 'CRITICAL')
  const warningAlerts = alerts.filter(a => a.severity === 'WARNING')
  const infoAlerts = alerts.filter(a => a.severity === 'INFO')



  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'DANGER': return '🚨'
      case 'CRITICAL': return '⚠️'
      case 'WARNING': return '⚡'
      case 'INFO': return 'ℹ️'
      default: return '📢'
    }
  }

  return `
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alertas NCF - ${businessSettings.name}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 20px; background-color: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { max-width: 150px; height: auto; margin-bottom: 10px; }
        .alert-section { margin-bottom: 30px; }
        .alert-section h3 { color: #1f2937; margin-bottom: 15px; padding-bottom: 5px; border-bottom: 1px solid #e5e7eb; }
        .alert-item { margin-bottom: 15px; padding: 15px; border-radius: 8px; border-left: 4px solid; }
        .alert-message { margin: 0; font-weight: 500; }
        .alert-details { margin-top: 8px; font-size: 14px; color: #6b7280; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 14px; color: #6b7280; }
        .action-button { display: inline-block; background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-top: 20px; }
        .critical { background-color: #fef2f2; border-left-color: #dc2626; }
        .warning { background-color: #fefce8; border-left-color: #d97706; }
        .info { background-color: #f0fdf4; border-left-color: #059669; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            ${businessSettings.logo ? `<img src="${businessSettings.logo}" alt="${businessSettings.name}" class="logo">` : ''}
            <h1>🚨 Alertas NCF - ${businessSettings.name}</h1>
            <p>Notificación automática del sistema de control fiscal</p>
        </div>

        ${criticalAlerts.length > 0 ? `
        <div class="alert-section">
            <h3>🚨 Problemas Críticos Requiren Atención Inmediata</h3>
            ${criticalAlerts.map(alert => `
            <div class="alert-item critical">
                <p class="alert-message">${getSeverityIcon(alert.severity)} ${alert.message}</p>
                <div class="alert-details">
                    <strong>Tipo de NCF:</strong> ${alert.sequenceType}<br>
                    ${alert.daysLeft !== undefined ? `<strong>Días restantes:</strong> ${alert.daysLeft}<br>` : ''}
                    ${alert.remaining !== undefined ? `<strong>Números restantes:</strong> ${alert.remaining}<br>` : ''}
                    <strong>Acción requerida:</strong> ${alert.actionRequired ? 'Sí' : 'No'}
                </div>
            </div>
            `).join('')}
        </div>
        ` : ''}

        ${warningAlerts.length > 0 ? `
        <div class="alert-section">
            <h3>⚠️ Advertencias - Revisar Pronto</h3>
            ${warningAlerts.map(alert => `
            <div class="alert-item warning">
                <p class="alert-message">${getSeverityIcon(alert.severity)} ${alert.message}</p>
                <div class="alert-details">
                    <strong>Tipo de NCF:</strong> ${alert.sequenceType}<br>
                    ${alert.daysLeft !== undefined ? `<strong>Días restantes:</strong> ${alert.daysLeft}<br>` : ''}
                    ${alert.remaining !== undefined ? `<strong>Números restantes:</strong> ${alert.remaining}<br>` : ''}
                    <strong>Acción requerida:</strong> ${alert.actionRequired ? 'Sí' : 'No'}
                </div>
            </div>
            `).join('')}
        </div>
        ` : ''}

        ${infoAlerts.length > 0 ? `
        <div class="alert-section">
            <h3>ℹ️ Información General</h3>
            ${infoAlerts.map(alert => `
            <div class="alert-item info">
                <p class="alert-message">${getSeverityIcon(alert.severity)} ${alert.message}</p>
                <div class="alert-details">
                    <strong>Tipo de NCF:</strong> ${alert.sequenceType}<br>
                    ${alert.daysLeft !== undefined ? `<strong>Días restantes:</strong> ${alert.daysLeft}<br>` : ''}
                    ${alert.remaining !== undefined ? `<strong>Números restantes:</strong> ${alert.remaining}<br>` : ''}
                    <strong>Acción requerida:</strong> ${alert.actionRequired ? 'Sí' : 'No'}
                </div>
            </div>
            `).join('')}
        </div>
        ` : ''}

        <div style="text-align: center; margin: 30px 0;">
            <a href="${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/ncf-monitor" class="action-button">
                Ver Panel de Control NCF
            </a>
        </div>

        <div class="footer">
            <p><strong>${businessSettings.name}</strong></p>
            <p>RNC: ${businessSettings.rnc}</p>
            <p>${businessSettings.address}</p>
            <p>Tel: ${businessSettings.phone} | Email: ${businessSettings.email}</p>
            <p style="margin-top: 15px; font-size: 12px; color: #9ca3af;">
                Esta es una notificación automática del sistema POS.<br>
                No responda a este correo electrónico.
            </p>
        </div>
    </div>
</body>
</html>
  `
}

// Send NCF alert email
async function sendNCFAlertEmail(alerts: AlertData[], recipients: string[], businessSettings: BusinessSettings): Promise<boolean> {
  try {
    const transporter = createTransporter()

    // Verify connection
    await transporter.verify()

    const emailHTML = generateNCFAlertEmailHTML(alerts, businessSettings)

    const criticalCount = alerts.filter(a => a.severity === 'DANGER' || a.severity === 'CRITICAL').length
    const subject = criticalCount > 0
      ? `🚨 ALERTA CRÍTICA NCF - ${criticalCount} problema(s) requieren atención inmediata`
      : `⚠️ Notificación NCF - ${alerts.length} alerta(s) detectada(s)`

    const mailOptions = {
      from: `"${businessSettings.name} - Sistema POS" <${loadEmailConfig().user}>`,
      to: recipients.join(', '),
      subject,
      html: emailHTML
    }

    const result = await transporter.sendMail(mailOptions)
    console.log('NCF alert email sent successfully:', result.messageId)

    return true
  } catch (error) {
    console.error('Error sending NCF alert email:', error)
    return false
  }
}

/**
 * POST /api/ncf/alerts/send - Send NCF alert notifications via email
 */
export async function POST(req: NextRequest) {
  const session = await getSessionFromCookie()
  if (!session) {
    return new NextResponse(JSON.stringify({ error: "Unauthorized" }), { status: 401 })
  }

  // Only admins can send alert emails
  if (session.role !== 'ADMIN') {
    return new NextResponse(JSON.stringify({ error: "Insufficient permissions" }), { status: 403 })
  }

  try {
    const { recipients, alerts } = await req.json()

    if (!recipients || !Array.isArray(recipients) || recipients.length === 0) {
      return new NextResponse(JSON.stringify({ error: "Recipients list is required" }), { status: 400 })
    }

    if (!alerts || !Array.isArray(alerts) || alerts.length === 0) {
      return new NextResponse(JSON.stringify({ error: "Alerts list is required" }), { status: 400 })
    }

    // Get business settings
    const businessSettings = await getBusinessSettings()

    // Send email
    const emailSent = await sendNCFAlertEmail(alerts, recipients, businessSettings)

    if (emailSent) {
      // Log the email sending
      await prisma.auditLog.create({
        data: {
          userId: session.userId,
          action: 'EMAIL_SENT',
          entity: 'NCF_ALERTS',
          entityId: 'notification',
          newValue: JSON.stringify({
            recipients: recipients.length,
            alertsCount: alerts.length,
            timestamp: new Date().toISOString()
          })
        }
      })

      return NextResponse.json({
        success: true,
        message: `Notificación enviada exitosamente a ${recipients.length} destinatario(s)`
      })
    } else {
      return new NextResponse(JSON.stringify({ error: "Failed to send email notification" }), { status: 500 })
    }

  } catch (error) {
    console.error('Error sending NCF alert notification:', error)
    return new NextResponse(JSON.stringify({ error: 'Server error' }), { status: 500 })
  }
}