import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { getSessionFromCookie } from "@/lib/session"
import { NCFType } from "@/lib/ncf"
import nodemailer from 'nodemailer'
import fs from 'fs'
import path from 'path'

interface AlertData {
  type: string
  message: string
  severity: 'INFO' | 'WARNING' | 'CRITICAL' | 'DANGER'
  sequenceType: NCFType
  daysLeft?: number
  remaining?: number
  actionRequired: boolean
  autoGenerated: boolean
}

const CONFIG_FILE = path.join(process.cwd(), 'email-config.json')

interface BusinessSettings {
  name: string;
  rnc: string;
  address: string;
  phone: string;
  email: string;
  logo?: string;
}

// Get business settings from database
async function getBusinessSettings() {
  const settings = await prisma.setting.findMany({
    where: {
      key: {
        in: ['business_name', 'business_rnc', 'business_address', 'business_phone', 'business_email', 'business_logo']
      }
    }
  })

  const businessData: {
    name: string
    rnc: string
    address: string
    phone: string
    email: string
    logo?: string
  } = {
    name: 'GNTech Demo',
    rnc: '000-00000-0',
    address: 'Santo Domingo, República Dominicana',
    phone: '809-555-5555',
    email: 'info@gntech.com',
    logo: undefined
  }

  // Override with database values
  settings.forEach((setting: { key: string; value: string }) => {
    switch (setting.key) {
      case 'business_name':
        businessData.name = setting.value
        break
      case 'business_rnc':
        businessData.rnc = setting.value
        break
      case 'business_address':
        businessData.address = setting.value
        break
      case 'business_phone':
        businessData.phone = setting.value
        break
      case 'business_email':
        businessData.email = setting.value
        break
      case 'business_logo':
        businessData.logo = setting.value
        break
    }
  })

  return businessData
}

// Load email configuration from file
function loadEmailConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      const configData = fs.readFileSync(CONFIG_FILE, 'utf8')
      return JSON.parse(configData)
    }
  } catch (error) {
    console.error('Error loading email config:', error)
  }

  // Fallback to environment variables
  return {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true',
    tls: process.env.SMTP_TLS !== 'false',
    timeout: process.env.SMTP_TIMEOUT || '30000',
    user: process.env.SMTP_USER || '',
    password: process.env.SMTP_PASS || '',
    senderName: process.env.SMTP_SENDER_NAME || 'Sistema POS - GNTech'
  }
}

// Create email transporter
function createTransporter() {
  const emailConfig = loadEmailConfig()

  return nodemailer.createTransport({
    host: emailConfig.host,
    port: parseInt(emailConfig.port.toString()),
    secure: emailConfig.secure || parseInt(emailConfig.port.toString()) === 465,
    requireTLS: emailConfig.tls,
    tls: {
      // Office365 compatible TLS settings
      minVersion: 'TLSv1.2',
      ciphers: 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384',
      rejectUnauthorized: false // Allow Office365 certificates
    },
    auth: {
      user: emailConfig.user,
      pass: emailConfig.password || process.env.SMTP_PASS || ''
    },
    connectionTimeout: parseInt(emailConfig.timeout || '30000'),
    greetingTimeout: 30000,
    socketTimeout: parseInt(emailConfig.timeout || '30000'),
    debug: process.env.NODE_ENV === 'development',
    logger: process.env.NODE_ENV === 'development'
  })
}

// Generate HTML email template for NCF alerts (simplified version for automated alerts)
function generateNCFAlertEmailHTML(alerts: AlertData[], businessSettings: BusinessSettings): string {
  const criticalAlerts = alerts.filter(a => a.severity === 'DANGER' || a.severity === 'CRITICAL')
  const warningAlerts = alerts.filter(a => a.severity === 'WARNING')

  return `
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alertas NCF Automáticas - ${businessSettings.name}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 20px; background-color: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .alert-section { margin-bottom: 30px; }
        .alert-section h3 { color: #1f2937; margin-bottom: 15px; padding-bottom: 5px; border-bottom: 1px solid #e5e7eb; }
        .alert-item { margin-bottom: 15px; padding: 15px; border-radius: 8px; border-left: 4px solid; }
        .alert-message { margin: 0; font-weight: 500; }
        .alert-details { margin-top: 8px; font-size: 14px; color: #6b7280; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 14px; color: #6b7280; }
        .action-button { display: inline-block; background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-top: 20px; }
        .critical { background-color: #fef2f2; border-left-color: #dc2626; }
        .warning { background-color: #fefce8; border-left-color: #d97706; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚨 Alertas NCF Automáticas</h1>
            <p>Notificación automática del sistema de control fiscal</p>
            <p style="color: #6b7280; font-size: 14px;">${businessSettings.name}</p>
        </div>

        ${criticalAlerts.length > 0 ? `
        <div class="alert-section">
            <h3>🚨 Problemas Críticos Requiren Atención Inmediata</h3>
            ${criticalAlerts.map(alert => `
            <div class="alert-item critical">
                <p class="alert-message">🚨 ${alert.message}</p>
                <div class="alert-details">
                    <strong>Tipo de NCF:</strong> ${alert.sequenceType}<br>
                    ${alert.daysLeft !== undefined ? `<strong>Días restantes:</strong> ${alert.daysLeft}<br>` : ''}
                    ${alert.remaining !== undefined ? `<strong>Números restantes:</strong> ${alert.remaining}<br>` : ''}
                </div>
            </div>
            `).join('')}
        </div>
        ` : ''}

        ${warningAlerts.length > 0 ? `
        <div class="alert-section">
            <h3>⚠️ Advertencias - Revisar Pronto</h3>
            ${warningAlerts.map(alert => `
            <div class="alert-item warning">
                <p class="alert-message">⚠️ ${alert.message}</p>
                <div class="alert-details">
                    <strong>Tipo de NCF:</strong> ${alert.sequenceType}<br>
                    ${alert.daysLeft !== undefined ? `<strong>Días restantes:</strong> ${alert.daysLeft}<br>` : ''}
                    ${alert.remaining !== undefined ? `<strong>Números restantes:</strong> ${alert.remaining}<br>` : ''}
                </div>
            </div>
            `).join('')}
        </div>
        ` : ''}

        <div style="text-align: center; margin: 30px 0;">
            <a href="${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/ncf-monitor" class="action-button">
                Ver Panel de Control NCF
            </a>
        </div>

        <div class="footer">
            <p><strong>${businessSettings.name}</strong></p>
            <p>RNC: ${businessSettings.rnc} | ${businessSettings.email}</p>
            <p style="margin-top: 15px; font-size: 12px; color: #9ca3af;">
                Esta es una notificación automática del sistema POS.<br>
                Generada el ${new Date().toLocaleDateString('es-DO')}
            </p>
        </div>
    </div>
</body>
</html>
  `
}

// Send automated NCF alert email
async function sendAutomatedNCFAlertEmail(alerts: AlertData[], businessSettings: BusinessSettings): Promise<boolean> {
  try {
    // Get admin users for email notifications
    const adminUsers = await prisma.user.findMany({
      where: { role: 'ADMIN' },
      select: { email: true, name: true }
    })

    const recipients = adminUsers
      .map((user: { email: string | null; name: string | null }) => user.email)
      .filter((email: string | null) => email && email.includes('@')) // Basic email validation

    if (recipients.length === 0) {
      console.warn('No valid admin email addresses found for NCF alerts')
      return false
    }

    const transporter = createTransporter()

    // Verify connection
    await transporter.verify()

    const emailHTML = generateNCFAlertEmailHTML(alerts, businessSettings)

    const criticalCount = alerts.filter(a => a.severity === 'DANGER' || a.severity === 'CRITICAL').length
    const subject = criticalCount > 0
      ? `🚨 ALERTA CRÍTICA NCF - ${criticalCount} problema(s) requieren atención inmediata`
      : `⚠️ Notificación NCF Automática - ${alerts.length} alerta(s) detectada(s)`

    const mailOptions = {
      from: `"${businessSettings.name} - Sistema POS" <${loadEmailConfig().user}>`,
      to: recipients.join(', '),
      subject,
      html: emailHTML
    }

    const result = await transporter.sendMail(mailOptions)
    console.log('Automated NCF alert email sent successfully:', result.messageId)

    return true
  } catch (error) {
    console.error('Error sending automated NCF alert email:', error)
    return false
  }
}

/**
 * GET /api/ncf/alerts - Get active NCF alerts
 */
export async function GET(_request: NextRequest) {
  const session = await getSessionFromCookie()
  if (!session) {
    return new NextResponse(JSON.stringify({ error: "Unauthorized" }), { status: 401 })
  }

  // Only admins and managers can access alerts
  if (!['ADMIN', 'MANAGER'].includes(session.role)) {
    return new NextResponse(JSON.stringify({ error: "Insufficient permissions" }), { status: 403 })
  }

  try {
    const sequences = await prisma.nCFSequence.findMany({
      orderBy: { type: 'asc' }
    })

    const now = new Date()
    const alerts: AlertData[] = []

    for (const sequence of sequences) {
      const expiryDate = new Date(sequence.expiryDate)
      const daysLeft = Math.ceil((expiryDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24))
      const remaining = sequence.endNumber - sequence.currentNumber

      // Check for expired sequences
      if (daysLeft < 0) {
        alerts.push({
          type: 'EXPIRED',
          message: `La secuencia NCF ${sequence.type} ha EXPIRADO. Ya no se pueden generar más NCF de este tipo.`,
          severity: 'DANGER',
          sequenceType: sequence.type as NCFType,
          daysLeft,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      }
      // Check for sequences expiring in 7 days or less (Critical)
      else if (daysLeft <= 7) {
        alerts.push({
          type: 'EXPIRING_SOON',
          message: `La secuencia NCF ${sequence.type} expira en ${daysLeft} día${daysLeft === 1 ? '' : 's'}. RENOVACIÓN URGENTE REQUERIDA.`,
          severity: 'CRITICAL',
          sequenceType: sequence.type as NCFType,
          daysLeft,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      }
      // Check for sequences expiring in 30 days or less (Warning)
      else if (daysLeft <= 30) {
        alerts.push({
          type: 'EXPIRING_SOON',
          message: `La secuencia NCF ${sequence.type} expira en ${daysLeft} días. Considera renovar pronto.`,
          severity: 'WARNING',
          sequenceType: sequence.type as NCFType,
          daysLeft,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      }

      // Check for low stock sequences
      if (remaining < 20) {
        const severity = remaining < 10 ? 'CRITICAL' : 'WARNING'
        alerts.push({
          type: 'LOW_STOCK',
          message: `La secuencia NCF ${sequence.type} tiene muy pocos números disponibles (${remaining} restantes).`,
          severity,
          sequenceType: sequence.type as NCFType,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      } else if (remaining < 100) {
        alerts.push({
          type: 'LOW_STOCK',
          message: `La secuencia NCF ${sequence.type} tiene pocos números disponibles (${remaining} restantes).`,
          severity: 'WARNING',
          sequenceType: sequence.type as NCFType,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      }

      // Check for exhausted sequences
      if (remaining <= 0) {
        alerts.push({
          type: 'EXHAUSTED',
          message: `La secuencia NCF ${sequence.type} se ha AGOTADO. No se pueden generar más NCF de este tipo.`,
          severity: 'DANGER',
          sequenceType: sequence.type as NCFType,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      }
    }

    // Sort alerts by severity (DANGER > CRITICAL > WARNING > INFO)
    const severityOrder = { 'DANGER': 4, 'CRITICAL': 3, 'WARNING': 2, 'INFO': 1 }
    alerts.sort((a, b) => severityOrder[b.severity] - severityOrder[a.severity])

    return NextResponse.json({
      data: alerts,
      summary: {
        total: alerts.length,
        danger: alerts.filter(a => a.severity === 'DANGER').length,
        critical: alerts.filter(a => a.severity === 'CRITICAL').length,
        warning: alerts.filter(a => a.severity === 'WARNING').length,
        info: alerts.filter(a => a.severity === 'INFO').length
      },
      timestamp: now.toISOString()
    })
  } catch (error) {
    console.error('Error fetching NCF alerts:', error)
    return new NextResponse(JSON.stringify({ error: 'Server error' }), { status: 500 })
  }
}

/**
 * POST /api/ncf/alerts/check - Trigger alert check (simulates cron job)
 */
export async function POST(_request: NextRequest) {
  const session = await getSessionFromCookie()
  if (!session) {
    return new NextResponse(JSON.stringify({ error: "Unauthorized" }), { status: 401 })
  }

  // Only admins can trigger automated checks
  if (session.role !== 'ADMIN') {
    return new NextResponse(JSON.stringify({ error: "Insufficient permissions" }), { status: 403 })
  }

  try {
    const sequences = await prisma.nCFSequence.findMany()
    const now = new Date()
    const alerts: AlertData[] = []
    let criticalIssues = 0

    for (const sequence of sequences) {
      const expiryDate = new Date(sequence.expiryDate)
      const daysLeft = Math.ceil((expiryDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24))
      const remaining = sequence.endNumber - sequence.currentNumber

      if (daysLeft < 0 || remaining <= 0) {
        criticalIssues++
      }

      // Generate alerts for critical issues
      if (daysLeft < 0) {
        alerts.push({
          type: 'EXPIRED',
          message: `CRÍTICO: Secuencia NCF ${sequence.type} EXPIRADA. Sistema pausado para este tipo.`,
          severity: 'DANGER',
          sequenceType: sequence.type as NCFType,
          daysLeft,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      } else if (remaining <= 0) {
        alerts.push({
          type: 'EXHAUSTED',
          message: `CRÍTICO: Secuencia NCF ${sequence.type} AGOTADA. No se pueden generar más NCF.`,
          severity: 'DANGER',
          sequenceType: sequence.type as NCFType,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      } else if (daysLeft <= 7) {
        alerts.push({
          type: 'EXPIRING_SOON',
          message: `URGENTE: NCF ${sequence.type} expira en ${daysLeft} días. Renovar inmediatamente.`,
          severity: 'CRITICAL',
          sequenceType: sequence.type as NCFType,
          daysLeft,
          remaining,
          actionRequired: true,
          autoGenerated: true
        })
      }
    }

    // Log the automated check
    await prisma.auditLog.create({
      data: {
        userId: session.userId,
        action: 'AUTO_CHECK',
        entity: 'NCF',
        entityId: 'alerts',
        newValue: JSON.stringify({
          alertsGenerated: alerts.length,
          criticalIssues,
          sequencesChecked: sequences.length,
          timestamp: now.toISOString()
        })
      }
    })

    // TODO: Here you could integrate with email notifications, SMS, or push notifications
    // For now, we just return the alerts

    // Send automated email notifications for critical alerts
    const criticalAlerts = alerts.filter(a => a.severity === 'DANGER' || a.severity === 'CRITICAL')
    if (criticalAlerts.length > 0) {
      try {
        const businessSettings = await getBusinessSettings()
        const emailSent = await sendAutomatedNCFAlertEmail(criticalAlerts, businessSettings)
        if (emailSent) {
          console.log(`Automated NCF alert email sent for ${criticalAlerts.length} critical issues`)
        }
      } catch (emailError) {
        console.error('Failed to send automated NCF alert email:', emailError)
        // Don't fail the entire request if email fails
      }
    }

    return NextResponse.json({
      success: true,
      alerts,
      criticalIssues,
      sequencesChecked: sequences.length,
      emailSent: criticalAlerts.length > 0,
      message: criticalIssues > 0 
        ? `Se detectaron ${criticalIssues} problema(s) crítico(s) que requieren atención inmediata. ${criticalAlerts.length > 0 ? 'Notificación por email enviada.' : ''}`
        : 'Verificación automática completada sin problemas críticos.'
    })
  } catch (error) {
    console.error('Error during automated NCF alert check:', error)
    return new NextResponse(JSON.stringify({ error: 'Server error' }), { status: 500 })
  }
}